### ISSUE TITLE
Vấn đề React Native for iOS 7.0 & Android 4.1

### ISSUE THREAD

**Issue by leovinh** [WomiApp/Womi#1]
@huynhloc Hiện tại App mình chỉ chạy trên iOS > 9.0. Điều này là 1 bất lợi lớn. Trong thông báo chính thức, Facebook có ghi: "Supported operating systems are >= Android 4.1 (API 16) and >= iOS 7.0." Ref: [https://github.com/facebook/react-native](url)

Ok next step:
- [ ] Tham khảo các app RN trên showcase: [https://facebook.github.io/react-native/showcase.html](url) 
- [ ] Test evaNews trên AWS test farm để xem có chạy ok trên iOS 7, 8 hay ko.
- [ ] Ask [https://www.facebook.com/groups/react.native.community/](url)

**Comment by huynhloc** [comment]
Em cũng mới thấy cái này lúc sáng.
Để xem lại xem nó bị vấn đề gì.

2016-04-10 13:34 GMT+07:00 Kevin Duong <notifications@github.com>:
